#!/usr/bin/env python3
"""
Copy embedding-related variables from FormatForge .env → .env.antfly for native Antfly/Termite.

Use with systemd EnvironmentFile=, or before starting Termite:  set -a && source .env.antfly && set +a

Also trims trailing whitespace on values in the root .env (fixes broken OPENROUTER_API_KEY lines).

Usage (from repo root):  python3 scripts/sync_antfly_env.py
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

KEYS = (
    "OPENROUTER_API_KEY",
    "EMBED_MODEL",
    "OPENAI_API_KEY",
    "OLLAMA_HOST",
    "ANTFLY_API_KEY",
    "ANTFLY_TERMITE_URL",
)


def load_env(path: Path) -> dict[str, str]:
    env: dict[str, str] = {}
    if not path.is_file():
        return env
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        m = re.match(r"^([A-Za-z_][A-Za-z0-9_]*)=(.*)$", line)
        if m:
            env[m.group(1)] = m.group(2).strip().strip('"').strip("'")
    return env


def strip_trailing_whitespace_on_values(path: Path) -> bool:
    """Remove trailing spaces/tabs from KEY=value values in place."""
    if not path.is_file():
        return False
    raw = path.read_text(encoding="utf-8")
    lines = raw.splitlines()
    new_lines: list[str] = []
    changed = False
    for line in lines:
        m = re.match(r"^([A-Za-z_][A-Za-z0-9_]*)=(.*)$", line)
        if m:
            k, v = m.group(1), m.group(2)
            sv = v.rstrip(" \t")
            if sv != v:
                changed = True
                line = f"{k}={sv}"
        new_lines.append(line)
    if changed:
        out = "\n".join(new_lines)
        if raw.endswith("\n"):
            out += "\n"
        path.write_text(out, encoding="utf-8")
    return changed


def build_lines(env: dict[str, str]) -> list[str]:
    lines = [
        "# Generated by scripts/sync_antfly_env.py — do not commit.",
        "",
    ]
    for k in KEYS:
        v = env.get(k, "").strip()
        if v:
            lines.append(f"{k}={v}")
    if not env.get("EMBED_MODEL"):
        lines.append("EMBED_MODEL=google/gemini-embedding-001")
    if not any(env.get(k) for k in ("OPENROUTER_API_KEY", "OPENAI_API_KEY")):
        lines.append(
            "# Warning: no OPENROUTER_API_KEY or OPENAI_API_KEY in .env — Termite OpenRouter embedder will fail."
        )
    return lines


def main() -> int:
    root = Path(__file__).resolve().parent.parent
    src = root / ".env"
    if strip_trailing_whitespace_on_values(src):
        print("Trimmed trailing whitespace in .env", file=sys.stderr)
    env = load_env(src)
    body = "\n".join(build_lines(env)) + "\n"
    out = root / ".env.antfly"
    out.write_text(body, encoding="utf-8")
    try:
        out.chmod(0o600)
    except OSError:
        pass
    print(out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
